In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

**Load Data set**

In [11]:
# Load Iris Dataset
data = load_iris()

# Get features and target
X = data.data
y = data.target

print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [5]:
print(X[:5])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
# Get dummy variable 
y = pd.get_dummies(y).values

print(y[:3])

[[ True False False]
 [ True False False]
 [ True False False]]


In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [15]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)  # 4 nodes in the hidden layer
        self.bias1 = np.random.rand(1, 4)  # Bias for the hidden layer
        self.weights2 = np.random.rand(4, 1)  # 1 output node
        self.bias2 = np.random.rand(1, 1)  # Bias for the output layer
        self.y = y
        self.output = np.zeros(y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1) + self.bias1)
        self.output = sigmoid(np.dot(self.layer1, self.weights2) + self.bias2)

    def backpropagation(self):
        # Calculate the derivative of the loss function with respect to weights and biases
        d_weights2 = np.dot(self.layer1.T, (2 * (self.y - self.output) * sigmoid_derivative(self.output)))
        d_bias2 = np.sum(2 * (self.y - self.output) * sigmoid_derivative(self.output), axis=0, keepdims=True)
        
        d_weights1 = np.dot(
            self.input.T,
            (
                np.dot(2 * (self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                sigmoid_derivative(self.layer1)
            ))
        d_bias1 = np.sum(
            np.dot(2 * (self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) *
                sigmoid_derivative(self.layer1),
            axis=0, 
            keepdims=True)

        # Update the weights and biases
        self.weights1 += d_weights1
        self.bias1 += d_bias1
        self.weights2 += d_weights2
        self.bias2 += d_bias2

In [16]:
X = np.array([[0, 0],
                [0, 1],
                [1, 0],
                [1, 1]])
y = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(X, y)

for i in range(1500):  # Number of epochs
    nn.feedforward()
    nn.backpropagation()

print(nn.output)


[[0.01954729]
 [0.97371976]
 [0.98283312]
 [0.0240839 ]]
